---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 08/04/2022 16:20
---

local commands = {};

function commands.SFOShouts(args, _)
    if args == "" then args = "1" end
    SFOShouts.macros[SFOShouts.currentBoss:gsub("[ ',]", "")](args);
end

for command, func in pairs(commands) do
    _G["SLASH_"..command:upper().."1"] = "/"..command;
    SlashCmdList[command:upper()] = func;
end

SFOShouts.commands = commands;