---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 08/04/2022 16:19
---

local events = {};

function events:ADDON_LOADED(AddonName)
    if AddonName == "SFOShouts" then
        print("[SFOShouts]: SFOShouts Loaded");
    end
end

function events:ENCOUNTER_START(encounterID, encounterName, difficultyID, groupSize)
    SFOShouts.currentBoss = encounterName;
end

function events:ENCOUNTER_END(encounterID, encounterName, difficultyID, groupSize)
    SFOShouts.currentBoss = "None";
end

SFOShouts.Frame:SetScript(
        "OnEvent",
        function(self, event, ...)
            events[event](self, ...);
        end
);

for event, _ in pairs(events) do
    SFOShouts.Frame:RegisterEvent(event);
end

SFOShouts.events = events;