---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 08/04/2022 00:37
---

local skada, details;
local currentBoss = "AnduinWrynn";
local macros = {};
local events = {};
local commands = {};
local SFOShoutsFrame = CreateFrame("Frame");

local waitTable = {};
local waitFrame

local function wait(delay, func, ...)
    local rval
    if(type(delay)~="number" or type(func)~="function") then
        return false;
    end
    if(waitFrame == nil) then
        waitFrame = CreateFrame("Frame","WaitFrame", UIParent);
        waitFrame:SetScript("onUpdate",function (self,elapse)
            local count = #waitTable;
            local i = 1;
            while(i<=count) do
                local waitRecord = tremove(waitTable,i);
                local d = tremove(waitRecord,1);
                local f = tremove(waitRecord,1);
                local p = tremove(waitRecord,1);
                if(d>elapse) then
                    tinsert(waitTable,i,{d-elapse,f,p});
                    i = i + 1;
                else
                    count = count - 1;
                    rval = f(unpack(p));
                end
            end
        end);
    end
    tinsert(waitTable,{delay,func,{...}});
    return rval;
end

function events:ADDON_LOADED(AddonName)
    if AddonName == "SFOShouts" then
        print("SFOShouts Loaded");
    end
end

local function getSkada()
    skada = Skada.current.mobname;
end

local function getDetails()
    details = Details.GetCombat():GetCombatName();
end

local function changeMacro()
    if details then
        currentBoss = details
    elseif skada then
        currentBoss = skada
    else
        print("[SFOShouts]: Details/Skada not present, /SFOShouts will not work")
    end
end

function macros.None()
    print("No Boss Engaged");
end

function macros.VigilantGuardian()
    print("No shout for vigilant guardian");
end

function macros.SkolextheInsatiableRavener()
    SendChatMessage("STACK FOR BURROW", "RAID_WARNING");
end

function macros.ArtificerXyMox()
    SendChatMessage("FOCUS ACOLYTE", "RAID_WARNING");
end

function macros.DausegnetheFallenOracle()
    print("No shout for Dausegne");
end

function macros.PrototypePantheon()
    SendChatMessage("FOCUS: "..UnitName("target"):upper(), "RAID_WARNING");
    SetRaidTarget("target", 8);
end

function macros.LihuvimPrincipalArchitect()
    SendChatMessage("FOCUS: "..UnitName("target"):upper(), "RAID_WARNING");
    SetRaidTarget("target", 8);
end

function macros.HalondrustheReclaimer()
    SendChatMessage("GET INFRONT OF ORB", "RAID_WARNING");
end

function macros.AnduinWrynn(cmd)
    if cmd == "1" then
        SendChatMessage("STACK IN BARRIER", "RAID_WARNING")
    elseif cmd == "2" then
        SendChatMessage("SPREAD", "RAID_WARNING")
    elseif cmd == "3" then
        SendChatMessage("STACK ON FALLEN KING", "RAID_WARNING")
    end
end

function commands.SFOShouts(args, _)
    if args == "" then args = "1" end
    macros[currentBoss:gsub("[ ',]", "")](args);
end

function events:PLAYER_REGEN_DISABLED()
    wait(0.01, pcall, getDetails);
    wait(0.01, pcall, getSkada);
    wait(0.02, changeMacro);
end

function events:PLAYER_REGEN_ENABLED()
    currentBoss = "None";
end

SFOShoutsFrame:SetScript(
        "OnEvent",
        function(self, event, ...)
            events[event](self, ...);
        end
);

for event, _ in pairs(events) do
    SFOShoutsFrame:RegisterEvent(event);
end

for command, func in pairs(commands) do
    _G["SLASH_"..command:upper().."1"] = "/"..command;
    SlashCmdList[command:upper()] = func
end