---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 08/04/2022 16:16
---

SFOShouts.waitTable = {};
SFOShouts.waitFrame = nil;

function SFOShouts.wait(delay, func, ...)
    local rval
    if(type(delay)~="number" or type(func)~="function") then
        return false;
    end
    if(SFOShouts.waitFrame == nil) then
        SFOShouts.waitFrame = CreateFrame("Frame","WaitFrame", UIParent);
        SFOShouts.waitFrame:SetScript("onUpdate",function (self,elapse)
            local count = #SFOShouts.waitTable;
            local i = 1;
            while(i<=count) do
                local waitRecord = tremove(SFOShouts.waitTable,i);
                local d = tremove(waitRecord,1);
                local f = tremove(waitRecord,1);
                local p = tremove(waitRecord,1);
                if(d>elapse) then
                    tinsert(SFOShouts.waitTable,i,{d-elapse,f,p});
                    i = i + 1;
                else
                    count = count - 1;
                    rval = f(unpack(p));
                end
            end
        end);
    end
    tinsert(SFOShouts.waitTable,{delay,func,{...}});
    return rval;
end

function SFOShouts.getSkada()
    SFOShouts.skada = Skada.current.mobname;
end

function SFOShouts.getDetails()
    SFOShouts.details = Details.GetCombat():GetCombatName();
end

function SFOShouts.changeMacro()
    if SFOShouts.details then
        SFOShouts.currentBoss = SFOShouts.details
    elseif skada then
        SFOShouts.currentBoss = SFOShouts.skada
    else
        print("[SFOShouts]: Details/Skada not present, /SFOShouts will not work")
    end
end