---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Zoë.
--- DateTime: 08/04/2022 16:16
---


function SFOShouts.getSkada()
    SFOShouts.skada = Skada.current.mobname;
end

function SFOShouts.getDetails()
    SFOShouts.details = Details.GetCombat():GetCombatName();
end

function SFOShouts.changeMacro()
    if SFOShouts.details then
        SFOShouts.currentBoss = SFOShouts.details
    elseif skada then
        SFOShouts.currentBoss = SFOShouts.skada
    else
        print("[SFOShouts]: Details/Skada not present, /SFOShouts will not work")
    end
end